project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

filters:
- nceas-learning-hub/theme
- quarto-ext/fontawesome
- shafayetShafee/line-highlight
exercises: ### for custom theme callouts
  number: true ### see https://cambiotraining.github.io/quarto-course-template/materials/02-content_guidelines.html
editor: source
execute:
  freeze: auto

format:
  theme-html:
    code-annotations: hover ### tool tip style footnotes for code
    link-external-newwindow: true
    link-external-icon: true

website:
  title: "2026 Delta Synthesis Working Groups week 3 (April 2026)"
  reader-mode: false
  repo-url: https://github.com/nceas-learning-hub/2026_delta_week3

  ### learning hub logo on browser tab
  favicon: _extensions/nceas-learning-hub/theme/banner/logo_favicon.png

  bread-crumbs: false
  navbar:
    right:
      - text: "Training Series"
        menu:
          - text: "Week 1"
            href: https://nceas-learning-hub.github.io/2026_delta_week1/
          - text: "Week 2"
            href: https://nceas-learning-hub.github.io/2026_delta_week2/
          - text: "Week 3"
            href: https://nceas-learning-hub.github.io/2026_delta_week3/
      - text: "Instructors"
        menu:
          - text: "Nick Lyon"
            href: https://njlyon0.github.io/
          - text: "Casey O'Hara"
            href: https://www.oharascience.com/
          - text: "Jim Regetz"
            href: https://github.com/regetz/
      - icon: github
        href: https://github.com/nceas-learning-hub/2026_delta_week3
        aria-label: GitHub

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/nceas-learning-hub/2026_delta_week3
    contents:
      - index.qmd # preface
      - s00_benchmarks.qmd
      # START SESSIONS
      - section: "Day 1"
        contents:
        - s01_lecture_publishing_data.qmd
        - s02_r_programmatic_data_access.qmd
      - section: "Day 2"
        contents:
        - s03_git_advanced_git_github.qmd
        - s04_lecture_science_communication.qmd
      - section: "Day 3"
        contents:
        - s05_shiny_introduction.qmd
        - s06_quarto_dashboards_reports.qmd
        - s07_quarto_websites.qmd
      - section: "Day 4"
        contents:
        - s08_r_tidymodels.qmd
        - s09_r_geospatial_raster_analysis.qmd
      # END SESSIONS

  page-footer:
    center: "Copyright \u00a9 2026, NCEAS"
    ### NCEAS main website footer:
    # center: "\u00a9 The Regents of the University of California, All Rights Reserved"
    # could also include license info?


