---
title: "Working Group Project Milestones"
---

## Overview

There are no universal benchmarks for how quickly a synthesis working group will proceed through the phases of a project's lifecycle. That said, the milestones below may prove helpful as a general 'how are we doing?' temperature check. If your group does not accomplish all of these--or proceeds beyond them--don't worry too much!

## Week 3 Benchmarks

:::{.panel-tabset}

### Before <u>Week 3</u>

Between the week 2 workshop and this workshop, <u>your group</u> should have done (at least some of) the following:

- Written code (version-controlled and stored in GitHub) to:
    - Harmonize/standardize your chosen datasets (can be a draft workflow at this point but should be pretty solid)
    - Perform preliminary analysis
    - Make publication-quality figures
- Finalized your group's authorship/intellectual credit policy
- Made a reasonably complete set of documentation explaining your project organization schema
- Considered whether custom R functions (or an R package) might make sense for your group's goals and interests
- Decided whether to make a group website (published via GitHub)

### At the End of Week 3

After this week, <u>your group</u> should have done (at least some of) the following:

- Begin planning for where your synthesized data should be archived for others to benefit from
- Written code (version-controlled and stored in GitHub) to:
    - Programmatically download data from online repositories (where applicable)
    - Perform more polished analysis
- Discussed possible avenues and strategies for communication about your project
- Considered whether to create an interactive Shiny app, Dashboard, etc.
- Built a team website with Quarto and GitHub Pages

And, most importantly, **your group should discuss how you want to move forward after the workshop series is complete!**

### After <u>Week 3</u>

After the third week of this workshop series, **we hope that your group uses the relevant skills from these workshops to pursue goals that feel meaningful to you.** Keep in mind that specific, actionable tasks are better than vague or open-ended goals but ultimately where you go from here is up to you!

Good luck!

:::
